### ISSUE TITLE
Interaction Stream

### ISSUE THREAD

**Issue by inzifusa** [LightBuzz/Kinect-HTML5#5]
Hi, 
I would like to use Kinect-HTML5 in my web application. 
How can I use interaction stream and controls for page navigation and interaction with page elements?

Thank you.

**Comment by Vangos** [comment]
Hello,

What kind of interaction stream do you mean? Currently, you can pass the joint coordinates, the color and depth frames as byte arrays.

**Comment by inzifusa** [comment]
Hello,
I would like to detect hand gestures (press, grip, scroll...), for example push a button, drag&drop an object.
I can't understand how to make this...

**Comment by Vangos** [comment]
You need mouse automation mechanisms. Check http://candescentnui.codeplex.com/.

**Comment by inzifusa** [comment]
Thank you for answer but I can't make Candescent NUI runs.
I'm searching for a simple way to control a web page for my degree thesis and I can't find a solution...
:(

**Comment by Vangos** [comment]
Hey. Why can't you use Candescent NUI? It is compatible with the Kinect SDK
and gives you the whole functionality you need.

On Wed, Apr 9, 2014 at 1:20 PM, inzifusa notifications@github.com wrote:

> Thank you for answer but I can't use Candescent NUI.
> I'm searching for a simple way to control a web page for my degree thesis
> and I can't find a solution...
> :(
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/LightBuzz/Kinect-HTML5/issues/5#issuecomment-39948734
> .

## 

Vangos Pterneas
Mobile: +30 694 498 1251
Website: pterneas.com

**Comment by inzifusa** [comment]
I would like to use it but doesn't run.
I have a Kinect for Xbox 360, windows 7, kinect sdk 1.8, openNi and Nite (last version, 64 bit).

When I try to open Mouse Control, an alert says "The environment variable could not be found".
I try to take a look at source code but I'm a C#  beginner.

Thank you very much

**Comment by Vangos** [comment]
Try to download the source code, go to the following file
http://candescentnui.codeplex.com/SourceControl/latest#CCT.NUI.KinectSDK/KinectSensorAdapter.cs

and comment-out the line: this.sensor.DepthStream.Range = DepthRange.Near;

I think it crashes because you have an XBOX sensor instead of a Windows
sensor. XBOX does not support Near mode, so if you comment-out that line
everything should work fine.

On Wed, Apr 9, 2014 at 3:56 PM, inzifusa notifications@github.com wrote:

> I would like to use it but doesn't run.
> I have a Kinect for Xbox 360, windows 7, kinect sdk 1.8, openNi and Nite
> (last version, 64 bit).
> 
> When I try to open Mouse Control, an alert says "The environment variable
> could not be found".
> I try to take a look at source code but I'm a C# beginner.
> 
> Thank you very much
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/LightBuzz/Kinect-HTML5/issues/5#issuecomment-39960151
> .

## 

Vangos Pterneas
Mobile: +30 694 498 1251
Website: pterneas.com

**Comment by inzifusa** [comment]
Done. Nothing change. 
Could be a problem with OpenNi 2?

**Comment by Vangos** [comment]
You need to have installed either the Kinect SDK or the OpenNI/NITE SDK.

On Wed, Apr 9, 2014 at 6:18 PM, inzifusa notifications@github.com wrote:

> Done. Nothing change.
> Could be a problem with OpenNi 2?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/LightBuzz/Kinect-HTML5/issues/5#issuecomment-39976410
> .

## 

Vangos Pterneas
Mobile: +30 694 498 1251
Website: pterneas.com

**Comment by inzifusa** [comment]
I have all installed

**Comment by Vangos** [comment]
Try to uninstall OpenNI and NITE.

On Wednesday, April 9, 2014, inzifusa notifications@github.com wrote:

> I have all installed
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/LightBuzz/Kinect-HTML5/issues/5#issuecomment-39981947
> .

## 

Vangos Pterneas
Mobile: +30 694 498 1251
Website: pterneas.com
